/**:
  ros__parameters:
    startup_px4_usb_quirk: false

# --- system plugins ---

# sys_status
/**/sys:
  ros__parameters:
    min_voltage: [10.0]   # diagnostics min voltage, use a vector i.e. [16.2, 16.0] for multiple batteries, up-to 10 are supported
                          # to achieve the same on a ROS launch file do: <rosparam param="sys/min_voltage">[16.2, 16.0]</rosparam>
    disable_diag: false   # disable all sys_status diagnostics, except heartbeat
    heartbeat_rate: 1.0   # send heartbeat rate in Hertz
    conn_timeout: 10.0    # heartbeat timeout in seconds

# sys_time
/**/time:
  ros__parameters:
    time_ref_source: "fcu"    # time_reference source
    timesync_mode: MAVLINK
    timesync_avg_alpha: 0.6   # timesync averaging factor
    timesync_rate: 100.0      # TIMESYNC rate in Hertz (feature disabled if 0.0)
    system_time_rate: 1.0     # send system time to FCU rate in Hertz (disabled if 0.0)

# --- mavros plugins (alphabetical order) ---

# command
/**/cmd:
  ros__parameters:
    use_comp_id_system_control: false   # quirk for some old FCUs

# global_position
/**/global_position:
  ros__parameters:
    frame_id: "map"                 # origin frame
    child_frame_id: "base_link"     # body-fixed frame
    rot_covariance: 99999.0         # covariance for attitude?
    gps_uere: 1.0                   # User Equivalent Range Error (UERE) of GPS sensor (m)
    use_relative_alt: true          # use relative altitude for local coordinates
    tf.send: FALSE                  # send TF?
    tf.frame_id: "map"              # TF frame_id
    tf.global_frame_id: "earth"     # TF earth frame_id
    tf.child_frame_id: "base_link"  # TF child_frame_id

# local_position
/**/local_position:
  ros__parameters:
    frame_id: "map"
    tf.send: true
    tf.frame_id: "map"
    tf.child_frame_id: "base_link"
    tf.send_fcu: false

# setpoint_accel
/**/setpoint_accel:
  ros__parameters:
    send_force: false

# setpoint_attitude
/**/setpoint_attitude:
  ros__parameters:
    reverse_thrust: false       # allow reversed thrust
    use_quaternion: false       # enable PoseStamped topic subscriber
    tf.listen: false            # enable tf listener (disable topic subscribers)
    tf.frame_id: "map"
    tf.child_frame_id: "target_attitude"
    tf.rate_limit: 50.0

# setpoint_position
/**/setpoint_position:
  ros__parameters:
    tf.listen: false            # enable tf listener (disable topic subscribers)
    tf.frame_id: "map"
    tf.child_frame_id: "target_position"
    tf.rate_limit: 50.0
    mav_frame: LOCAL_NED

# setpoint_velocity
/**/setpoint_velocity:
  ros__parameters:
    mav_frame: LOCAL_NED