/flychams/**:
  ros__parameters:
    global_frame: "world"
    agent_frames:
      agent_local: "AGENTID/map"
      agent_body: "AGENTID/base_link"
      camera_body: "AGENTID/HEADID/base_link"
      camera_optical: "AGENTID/HEADID/optical"