/flychams/**:
  ros__parameters:
    # Tracking parameters
    tracking:
      num_tracking_windows: 4 # For MultiWindowTracking mode
      kappa_s: 0.8            # Half-width fraction
      s_min_pix: 0.0          # Minimum apparent size of the target (pix)
    # Window IDs (for GUI purposes)
    window_ids:
      scene_id: "SCENE"
      agent_1_id: "AGENT_1"
      agent_2_id: "AGENT_2"
      map_id: "MAP"
      central_id: "CENTRAL"
      tracking_ids: [
        "TRACKING00",
        "TRACKING01",
        "TRACKING02",
        "TRACKING03"
        ]
    # Camera IDs (for GUI purposes)
    camera_ids:
      scene_id: "CAM_SCENE"
      agent_1_id: "CAM_AGENTID_1"
      agent_2_id: "CAM_AGENTID_2"