/flychams/**:
  ros__parameters:
    # Tracking parameters
    tracking:
      num_tracking_windows: 4 # For MultiWindowTracking mode
      kappa_s: 0.8            # Half-width fraction
      s_min_pix: 0.0          # Minimum apparent size of the target (pix)
    # Window IDs
    window_ids:
      scene_id: "SCENE"
      agent_id: "AGENT"
      data_id: "DATA"
      map_id: "MAP"
      central_id: "CENTRAL"
      tracking_ids: [
        "TRACKING00",
        "TRACKING01",
        "TRACKING02",
        "TRACKING03"
        ]
    camera_ids:
      scene_id: "SCENECAM"
      agent_id: "AGENTCAM_AGENTID"