/flychams/**:
  ros__parameters:
    # Tracking parameters
    tracking:
      num_tracking_windows: 4 # For MultiWindowTracking mode
      min_apparent_size: 0.2  # Minimum fraction of half-sensor that the target will occupy in the image
      max_apparent_size: 0.9  # Maximum fraction of half-sensor that the target will occupy in the image
      ref_apparent_size: 0.65  # Reference fraction of half-sensor that the target will occupy in the image
    # Window IDs (for GUI purposes)
    fixed_window_ids: ["SCENE", "AGENT00", "AGENT01", "MAP"]
    central_window_id: "CENTRAL"
    tracking_window_ids: ["TRACKING00", "TRACKING01", "TRACKING02", "TRACKING03"]
    # Fixed camera IDs (for GUI purposes)
    fixed_camera_ids: ["CAM_SCENE", "CAM_AGENTID_00", "CAM_AGENTID_01", ""]

