/flychams/**:
  ros__parameters:
    # Global topics
    global_topics:
      registration: "bringup/registration"                          # Registration.msg (custom)
      metrics: "dashboard/global/metrics"                           # GlobalMetrics.msg (custom)
    # Agent topics
    agent_topics:
      status: "control/AGENTID/status"                              # AgentStatus.msg (custom)
      position: "control/AGENTID/position"                          # PointStamped.msg
      assignment: "coordination/AGENTID/assignment"                 # AgentAssignment.msg (custom)
      clusters: "coordination/AGENTID/clusters"                     # AgentClusters.msg (custom)
      position_setpoint: "coordination/AGENTID/setpoint/position"   # PointStamped.msg
      tracking_setpoints: "coordination/AGENTID/setpoint/tracking"  # AgentTrackingSetpoints.msg (custom)
      metrics: "dashboard/AGENTID/metrics"                          # AgentMetrics.msg (custom)
      markers: "dashboard/AGENTID/markers"                          # MarkerArray.msg
    # Target topics
    target_topics:
      true_position: "targets/TARGETID/true_position"               # PointStamped.msg
      est_position: "perception/TARGETID/est_position"              # PointStamped.msg
      metrics: "dashboard/TARGETID/metrics"                         # TargetMetrics.msg (custom)
      markers: "dashboard/TARGETID/markers"                         # MarkerArray.msg
    # Cluster topics
    cluster_topics:
      assignment: "perception/CLUSTERID/assignment"                 # ClusterAssignment.msg (custom)
      geometry: "perception/CLUSTERID/geometry"                     # ClusterGeometry.msg (custom)
      metrics: "dashboard/CLUSTERID/metrics"                        # ClusterMetrics.msg (custom)
      markers: "dashboard/CLUSTERID/markers"                        # MarkerArray.msg
    # GUI topics
    gui_topics:
      setpoints: "simulation/AGENTID/setpoint/gui"                  # GuiSetpoints.msg (custom)