/flychams/**:
  ros__parameters:
    uav_control:
      # Update rates (Hz)
      control_update_rate: 10.0
      # Takeoff altitude (m)
      takeoff_altitude: 1.0
      # Timeouts (s)
      takeoff_timeout: 10.0
      landing_timeout: 10.0
      # Speed scheduling parameters
      min_speed: 2.0
      max_speed: 12.0
      min_distance: 0.25
      max_distance: 50.0
      max_acceleration: 1.0

    head_control:
      # Update rates (Hz)
      control_update_rate: 20.0