/flychams/**:
  ros__parameters:
    # Drone state parameters
    drone_state:
      update_rate: 5.0          # (Hz)
      takeoff_altitude: 1.0     # (m)
      takeoff_timeout: 10.0     # (s)
      landing_altitude: 0.5     # (m)
      landing_timeout: 10.0     # (s)
      hover_altitude: 1.0       # (m)
      hover_timeout: 5.0        # (s)

    # Drone motion parameters
    drone_control:
      update_rate: 10.0         # (Hz)
      control_mode: 0           # 0: position, 1: velocity
      min_speed: 1.0            # (m/s)
      max_speed: 3.0            # (m/s)
      min_distance: 0.10        # (m)
      max_distance: 20.0        # (m)
      max_acceleration: 0.2     # (m/s^2)
      
    # Head control parameters
    head_control:
      update_rate: 20.0 # (Hz)