/flychams/**:
  ros__parameters:
    # Agent assignment parameters
    agent_assignment:
      assignment_rate: 1.0    # (Hz)
      mode: 0                 # 0: greedy, 1: suboptimal
    # Agent analysis parameters
    agent_analysis:
      analysis_rate: 20.0       # (Hz)
    # Agent positioning parameters
    agent_positioning:
      positioning_rate: 10.0 # (Hz)
      # Solver parameters
      solver_mode: 0                    # 0: NLOPT_NELDER_MEAD
      convergence_tolerance: 1.0e-6     # Solver convergence tolerance
      max_iterations: 100               # Maximum number of iterations
      eps: 1.0                          # Threshold difference between solutions of successive iterations to terminate the algorithm
    # Agent tracking parameters
    agent_tracking:
      tracking_rate: 20.0 # (Hz)
