/flychams/**:
  ros__parameters:
    # Target state parameters
    target_state:
      state_update_rate: 20.0 # (Hz)
    # Target motion parameters
    target_motion:
      motion_update_rate: 20.0 # (Hz)